import re

with open("tampermonkey/nilam-api.user.js", "r", encoding="utf-8") as f:
    code = f.read()

# 1. Bump version
code = code.replace("// @version      0.7.3", "// @version      0.7.4")
code = code.replace('const SCRIPT_VERSION = "0.7.3";', 'const SCRIPT_VERSION = "0.7.4";')

# 2. Add findProfileData function before patchFetch
profile_logic = """
  function extractId(field) {
    if (!field) return undefined;
    if (typeof field === "number" || typeof field === "string") return Number(field);
    if (field.id) return Number(field.id);
    if (field.data && field.data.id) return Number(field.data.id);
    return undefined;
  }

  function findProfileData(obj, userId) {
    if (!obj || typeof obj !== "object") return null;
    
    const target = obj.attributes || obj;
    const student = extractId(target.student);
    const school = extractId(target.school);
    const cls = extractId(target.class) || extractId(target.classes);
    
    if (student && school) {
      return { student, school, class: cls };
    }

    for (const key in obj) {
      if (typeof obj[key] === "object") {
        const res = findProfileData(obj[key], userId);
        if (res) return res;
      }
    }
    return null;
  }

  function patchFetch() {"""
code = code.replace("function patchFetch() {", profile_logic)

# 3. Add the interception logic inside XHR load listener
interception_logic = """
          if ((url.includes("users/me") || url.includes("student-informations")) && String(method).toUpperCase() === "GET") {
            try {
              const data = JSON.parse(this.responseText);
              const profile = findProfileData(data, state.userId);
              if (profile && (!state.apiTemplate || state.apiTemplate.autoGenerated)) {
                console.log("NILAM API Assistant: Auto-extracted profile data ->", profile);
                state.apiTemplate = {
                  url: "https://ains-api.moe.gov.my/api/nilam-records/submit",
                  method: "POST",
                  headers: { 
                     "authorization": state.authHeader,
                     "content-type": "application/json",
                     "accept": "application/json, text/plain, */*"
                  },
                  bodyText: JSON.stringify({
                    data: {
                      type: "book",
                      bookType: "physical",
                      reviewIsVideo: false,
                      rating: 5,
                      user: Number(state.userId),
                      student: profile.student,
                      school: profile.school,
                      class: profile.class
                    }
                  }),
                  payload: null,
                  capturedAt: new Date().toISOString(),
                  autoGenerated: true
                };
                saveState();
                renderApiStatus();
                setStatus("凭证已静默捕获 (自动提取)！已就绪，可开始同步。");
              }
            } catch (e) {
              console.error("Failed to parse intercepted XHR profile response", e);
            }
          }
"""

# Insert it before the info/counter check inside patchXhr
search_str = """          if (url.includes("info/counter") && String(method).toUpperCase() === "GET") {"""
code = code.replace(search_str, interception_logic + "\n" + search_str)

# Also insert it for fetch API just in case they switch to fetch
interception_logic_fetch = interception_logic.replace("this.responseText", "await clone.clone().text()")
fetch_search_str = """        if (url.includes("info/counter") && String(method).toUpperCase() === "GET") {"""
code = code.replace(fetch_search_str, interception_logic_fetch + "\n" + fetch_search_str)


with open("tampermonkey/nilam-api.user.js", "w", encoding="utf-8") as f:
    f.write(code)

print("Migration to v0.7.4 with auto-capture completed.")
