import re

with open("tampermonkey/nilam-api.user.js", "r", encoding="utf-8") as f:
    code = f.read()

# 1. Bump version to 0.8.0 (major fix)
code = code.replace("// @version      0.7.5", "// @version      0.8.0")
code = code.replace('const SCRIPT_VERSION = "0.7.5";', 'const SCRIPT_VERSION = "0.8.0";')

# 2. Remove extractId and findProfileData
code = re.sub(r"  function extractId\(field\) \{.*?(?=  function patchFetch\(\) \{)", "", code, flags=re.DOTALL)

# 3. Remove the fetch interceptor for users/me
fetch_intercept = r"""        if \(\(url\.includes\("users/me"\) \|\| url\.includes\("student-informations"\)\) && String\(method\)\.toUpperCase\(\) === "GET"\) \{.*?          \} catch \(e\) \{.*?          \}
        \}

"""
code = re.sub(fetch_intercept, "", code, flags=re.DOTALL)

# 4. Remove the xhr interceptor for users/me
xhr_intercept = r"""          if \(\(url\.includes\("users/me"\) \|\| url\.includes\("student-informations"\)\) && String\(method\)\.toUpperCase\(\) === "GET"\) \{.*?            \} catch \(e\) \{.*?            \}
          \}

"""
code = re.sub(xhr_intercept, "", code, flags=re.DOTALL)

# 5. Inject auto-construct inside updateCapturedToken
token_logic = """
      if (state.apiTemplate) {
        state.apiTemplate.headers["authorization"] = authHeader;
        console.log("NILAM API Assistant: Automatically updated Bearer Token in background.");
      } else if (state.userId) {
        state.apiTemplate = {
          url: "https://ains-api.moe.gov.my/api/nilam-records/submit",
          method: "POST",
          headers: { 
             "authorization": authHeader,
             "content-type": "application/json",
             "accept": "application/json, text/plain, */*"
          },
          bodyText: JSON.stringify({
            data: {
              type: "book",
              bookType: "physical",
              reviewIsVideo: false,
              rating: 5,
              user: Number(state.userId)
            }
          }),
          payload: null,
          capturedAt: new Date().toISOString(),
          autoGenerated: true
        };
        console.log("NILAM API Assistant: Auto-constructed apiTemplate from Bearer token.");
        setTimeout(() => { if (state.userId) fetchHistory(); }, 500);
      }
"""
code = re.sub(r"""      if \(state\.apiTemplate\) \{\s*state\.apiTemplate\.headers\["authorization"\] = authHeader;\s*console\.log\("NILAM API Assistant: Automatically updated Bearer Token in background\."\);\s*\}""", token_logic, code)

with open("tampermonkey/nilam-api.user.js", "w", encoding="utf-8") as f:
    f.write(code)

print("Migration to v0.8.0 completed.")
